### ISSUE TITLE
Q: Does it work with the Xiaomi MI A2

### ISSUE THREAD

**Issue by JeromTWinL** [serdeliuk/edk2-lavender#1]
Does it work with the Xiaomi MI A2?
 Cuz it is also sdm660, even i wanna boot windows.

Did u know about that?

Thanks in reply.

**Comment by serdeliuk** [comment]
Hi, should work on any device with sdm630/636/660 CPU, if you succeed please let me know, on Lavender the USB does not work yet as is.

**Comment by JeromTWinL** [comment]
Ok, and if you can make Input System Disk, USB, Battery workable, then everyone will able to boot Windows 10/11 arm64 with the help of your repo, good luck.

**Comment by XRedCubeX** [comment]
I managed to adapt it for the Mi A2 some time ago but without the USB there is little to do

**Comment by serdeliuk** [comment]
> Ok, and if you can make Input System Disk, USB, Battery workable, then everyone will able to boot Windows 10/11 arm64 with the help of your repo, good luck.

Not sure what is that "Input System Disk", i was able to boot Windows from eMMC, Windows PE and Windows 11 installer, right now i am working to patch USB to have keyboard and mouse (I already have usb keyboard in EDK2), however ACPI tables should be fixed to have them working on windows, also, battery and anything else require working ACPI.
