### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by Uchiha-Peng** [serdeliuk/edk2-lavender#2]
Glad to see that you are porting EDK2 to Xiaomi Lavender, I see that some developers have tried to do the same thing before, maybe you can refer to it to avoid duplication of work, although it is a bit difficult, but I wish you an early success.

Maybe you can try to make it run a full Linux distribution like Debian, Ubuntu, that might be more useful and simpler.

https://github.com/dreemurrs-embedded/edk2-lavender

https://wiki.postmarketos.org/wiki/Xiaomi_Redmi_Note_7_(xiaomi-lavender)/Mainline_development

**Comment by serdeliuk** [comment]
Hi, thanks for heads-up, my repo is based on Danct12's (dreemurrs-embedded) initial work.

Nobody, until me, were able to make the eMMC to work on any XBL device, due to ClockDxe issues.
I have fixed ClockDxe and eMMC is working fine on sdm630/636/660 CPUS probably others too.

EDK2 is able to boot Windows or anything else that is EFI from eMMC.

I do not intend to work for a specific OS right now, currently i am struggling to fix USB efi drivers to have keyboard and mouse input in EDK2

**Comment by Uchiha-Peng** [comment]
Great developer, could you please upload the compiled file, thank you very much, unfortunately I don't know the relevant development, but I want to try to run it.

**Comment by serdeliuk** [comment]
Unfortunately i am not able to provide binary files, but all required to be able to build a working EDK2 image are in the release archive, if you follow the steps from the readme you can easily build an EDK2 whout have much troubles.

If you have issues, you can ask your questions on XDA thread `https://forum.xda-developers.com/t/info-edk2-port-to-redmi-note-7-to-boot-windows.4364063/`

**Comment by Uchiha-Peng** [comment]
alright, thank you very much .

**Comment by serdeliuk** [comment]
> alright, thank you very much .

You're quite welcome, just let me know if you have any issues, on XDA thread

**Comment by Uchiha-Peng** [comment]
OK, then I will close this issue.

**Comment by marohinmark** [comment]
I and Aboo Thahir mainlined Asus Zenfone Max Pro M1 on Snapdragon 636, will try to boot Ubuntu. Gpu doesn't work in Linux, and I do not have access to Danct12's 5.15

**Comment by Uchiha-Peng** [comment]
> 

I have compiled Xiaomi Lavender's uefi.img file, and I also want to try booting Ubuntu. Could you share the steps you tried to boot Ubuntu through UEFI grub, thank you very much.

![43c3bbdc811d9f841cae42171cfe888](https://user-images.githubusercontent.com/20633089/149140949-7e800046-6b05-4eed-a439-74a466c15a52.jpg)


[uefi.zip](https://github.com/serdeliuk/edk2-lavender/files/7854548/uefi.zip)

**Comment by Uchiha-Peng** [comment]
#### 
I suggest you update the README

1. Install dependencies

On Ubuntu 18.04
```
sudo apt install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu abootimg bspatch p7zip-full zip python-pip
```
On Debian 11
```
sudo apt install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu abootimg bspatch p7zip-full zip pip
```
sudo pip install uefi_firmware

2. Clone edk2 and edk2-platforms repositories

```
git clone https://github.com/tianocore/edk2.git --recursive

git clone https://github.com/tianocore/edk2-platforms.git
```
3. Download Released File and Unzip

```
wget https://github.com/serdeliuk/edk2-lavender/releases/download/2/edk2-lavender.0.0.2.zip
unzip edk2-lavender.0.0.2.zip
```

4. edit edk2-lavender/RedmiNote7Pkg/RedmiNote7Pkg.dsc. uncomment the line below that contain RegisterFilterLib

```
[LibraryClasses]
#  RegisterFilterLib|MdePkg/Library/RegisterFilterLibNull/RegisterFilterLibNull.inf
  VariablePolicyHelperLib|MdeModulePkg/Library/VariablePolicyHelperLib/VariablePolicyHelperLib.inf
```

Update to

```
  RegisterFilterLib|MdePkg/Library/RegisterFilterLibNull/RegisterFilterLibNull.inf
  VariablePolicyHelperLib|MdeModulePkg/Library/VariablePolicyHelperLib/VariablePolicyHelperLib.inf
```

5. place your xbl.elf extracted from a firmware update in xbl folder

6. run xbl-extract.sh inside xbl folder

7. run xbl-extract.sh inside xbl folder

8. run ` make -C your_path/edk2-lavender/../edk2/BaseTools/Source/C `

9. run ` bash build.sh `

10. run ` fastboot flash boot uefi.img `

**Comment by serdeliuk** [comment]
Hi, thanks, please update the XDA thread with all your concerns.

I do not intend to update any EDK2 related stuff right now i as i am still working on DXE drivers.

All EDK2 porting guides contain all required steps to do, to properly setup the EDK2 environment, depending on your OS, this is not something new, if you need to lean how is done you may need to seek assistance elsewhere.

From your image it seems that you successfully access your eMMC from your EDK2, you may need to create an FAT32 partition on your eMMC on which you may need to put your EFI folder with boot loader, if EDK2 will find the EFI folder will try to load the bootloader from there, but please, do NOT ask here question not related to my EDK2, if you need to run an OS you may need to seek resources on XDA, on the OS developments forums or websites or through Google, i am not supporting any OS right now, just testing Windows 10 for ARM until EDK2 EFI drivers will be complete.

Danct12 has a Discord channel for Lavender device and Linux, please ask them anything related to Linux. If you want Linux maybe EDK2 is not what you need to seek. Linux works already without EDK2 booting linux kernel.

**Comment by Uchiha-Peng** [comment]
Ok, I'll update to XDA when I'm free, sorry I'm asking  @serdeliuk  as he seems to be doing the same thing as me.
